---
kind: pipeline
name: default

steps:
- name: build
  image: docker
  when:
    branch:
      exclude:
        - skip-ci*
    event:
      exclude:
      - pull_request
      - tag
  environment:
    SSH_PRIVATE_KEY:
      from_secret: SSH_PRIVATE_KEY
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
  commands:
    - export DOCKER_HOST=unix:///var/run/host.sock
    - docker login -u 'robot$drone' -p $DOCKER_PASSWORD harbor.dsrd.libraries.psu.edu
    - docker build -t harbor.dsrd.libraries.psu.edu/library/ss-shrine:$DRONE_BUILD_NUMBER . 
    - docker tag harbor.dsrd.libraries.psu.edu/library/ss-shrine:$DRONE_BUILD_NUMBER harbor.dsrd.libraries.psu.edu/library/ss-shrine:ci
    - docker tag harbor.dsrd.libraries.psu.edu/library/ss-shrine:$DRONE_BUILD_NUMBER harbor.dsrd.libraries.psu.edu/library/ss-shrine:$DRONE_COMMIT_SHA
    - docker push harbor.dsrd.libraries.psu.edu/library/ss-shrine
  volumes:
  - name: docker-sock
    path: /var/run/host.sock

- name: tag
  image: alpine/git
  when:
    branch:
      exclude:
        - skip-ci*
    event:
      exclude:
      - pull_request
      - tag
  commands:
  - git config user.email "drone@drone2test.vmhost.psu.edu"
  - git config user.name "DroneCI"
  - sluggified=$(echo $DRONE_BRANCH | sed -e 's/[^[:alnum:]]/-/g' | tr -s '-' | tr A-Z a-z )
  - git tag -f $sluggified $DRONE_COMMIT_SHA 
  - git push --tags --force

services:
- name: postgres
  image: postgres:10
  when:
    branch:
      exclude:
        - skip-ci*
    event:
      exclude:
      - pull_request
      - tag
  environment:
    POSTGRES_PASSWORD: ss-shrine-test
    POSTGRES_USER: ss-shrine
    POSTGRES_DB: ss-shrine
  
volumes:
- name: docker-sock
  host:
    path: /var/run/docker.sock
