---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/instance: ss-shrine
  name: __FQDN__
spec:
  acme:
    config:
    - dns01:
        provider: route53
      domains:
      - __FQDN__
  commonName: __FQDN__
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod-route53
  secretName: __FQDN__
