---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ss-shrine
  labels:
    app: ss-shrine
    ref: develop
spec:
  tls:
    - secretName: __FQDN__
      hosts:
        - __FQDN__
  rules:
    - host: __FQDN__
      http:
        paths:
          - path: /
            backend:
              serviceName: ss-shrine
              servicePort: 3000
